
from .producto_views import * 
from .cliente_views import *
from .cliente_contactos_views import *
from .comunicacion_empresa_views import *
from .proveedor_views import *
from .cliente_credito_views import *
from .clase_views import *
from .linea_views import *
from .marca_views import * 
from .banco_views import *
from .cuenta_de_banco_views import *
from .producto_servicio_views import *
from .descuento_por_volumen_views import * 
from .lista_de_precios_venta_views import *
from .lista_de_precios_venta_det_views import *
from .precios_por_cliente_views import *
from .precios_por_cliente_det_views import *
from .socio_views import *