from .comprobante import Comprobante
from .emisor import Emisor
from .receptor import Receptor
from .conceptos import Conceptos
from .concepto import Concepto
from .impuestos import Impuestos
from .traslados import Traslados
from .traslado import Traslado
from .retencion import Retencion
from .retenciones import Retenciones
from .complemento import Complemento
from .impuestos10 import Impuestos10
from .traslados10 import Traslados10
from .traslado10 import Traslado10
from .retenciones10 import Retenciones10 
from .retencion10 import Retencion10