# Generated by Django 3.2 on 2023-01-06 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0002_perfilpruebas_usuariopruebas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilpruebas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='pruebas.usuariopruebas'),
        ),
    ]
